"""empty message

Revision ID: 3943b2f614d1
Revises: 4816815e5103
Create Date: 2024-01-19 19:42:31.455522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3943b2f614d1'
down_revision = '4816815e5103'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.drop_constraint('user_data_date_time_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_data_date_time_key', ['date_time'])

    # ### end Alembic commands ###
