"""empty message

Revision ID: 4816815e5103
Revises: fd8d8fb4e037
Create Date: 2024-01-19 19:25:16.053850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4816815e5103'
down_revision = 'fd8d8fb4e037'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.drop_constraint('user_data_liters_key', type_='unique')
        batch_op.drop_constraint('user_data_location_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_data_location_key', ['location'])
        batch_op.create_unique_constraint('user_data_liters_key', ['liters'])

    # ### end Alembic commands ###
