"""empty message

Revision ID: 9bbd51ddea4d
Revises: 3d2681a9eced
Create Date: 2024-01-29 19:46:09.080739

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9bbd51ddea4d'
down_revision = '3d2681a9eced'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=120), nullable=False))
        batch_op.drop_constraint('user_user_name_key', type_='unique')
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.drop_column('user_name')

    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('finish_time', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.Enum('pending', 'complete', 'invalid', name='statusenum'), nullable=False))
        batch_op.drop_column('date_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_column('status')
        batch_op.drop_column('finish_time')
        batch_op.drop_column('start_time')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('user_user_name_key', ['user_name'])
        batch_op.drop_column('username')

    # ### end Alembic commands ###
