"""empty message

Revision ID: fd8d8fb4e037
Revises: 14bb5c09389c
Create Date: 2024-01-19 18:46:13.620592

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fd8d8fb4e037'
down_revision = '14bb5c09389c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_time', sa.DateTime(), nullable=False))
        batch_op.drop_constraint('user_data_date_key', type_='unique')
        batch_op.drop_constraint('user_data_time_key', type_='unique')
        batch_op.create_unique_constraint(None, ['date_time'])
        batch_op.drop_column('time')
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('user_data_time_key', ['time'])
        batch_op.create_unique_constraint('user_data_date_key', ['date'])
        batch_op.drop_column('date_time')

    # ### end Alembic commands ###
